
export const CompoundMineral = {
    // 基础化合物
    [RESOURCE_HYDROXIDE]: { rct1: RESOURCE_HYDROGEN, rct2: RESOURCE_OXYGEN },
    [RESOURCE_ZYNTHIUM_KEANITE]: { rct1: RESOURCE_ZYNTHIUM, rct2: RESOURCE_KEANIUM },
    [RESOURCE_UTRIUM_LEMERGITE]: { rct1: RESOURCE_UTRIUM, rct2: RESOURCE_LEMERGIUM },
    [RESOURCE_GHODIUM]: { rct1: RESOURCE_ZYNTHIUM_KEANITE, rct2: RESOURCE_UTRIUM_LEMERGITE },

    // 一级化合物
    [RESOURCE_UTRIUM_HYDRIDE]: { rct1: RESOURCE_UTRIUM, rct2: RESOURCE_HYDROGEN },
    [RESOURCE_UTRIUM_OXIDE]: { rct1: RESOURCE_UTRIUM, rct2: RESOURCE_OXYGEN },
    [RESOURCE_ZYNTHIUM_OXIDE]: { rct1: RESOURCE_ZYNTHIUM, rct2: RESOURCE_OXYGEN },
    [RESOURCE_ZYNTHIUM_HYDRIDE]: { rct1: RESOURCE_ZYNTHIUM, rct2: RESOURCE_HYDROGEN },
    [RESOURCE_KEANIUM_OXIDE]: { rct1: RESOURCE_KEANIUM, rct2: RESOURCE_OXYGEN },
    [RESOURCE_KEANIUM_HYDRIDE]: { rct1: RESOURCE_KEANIUM, rct2: RESOURCE_HYDROGEN },
    [RESOURCE_LEMERGIUM_OXIDE]: { rct1: RESOURCE_LEMERGIUM, rct2: RESOURCE_OXYGEN },
    [RESOURCE_LEMERGIUM_HYDRIDE]: { rct1: RESOURCE_LEMERGIUM, rct2: RESOURCE_HYDROGEN },
    [RESOURCE_GHODIUM_OXIDE]: { rct1: RESOURCE_GHODIUM, rct2: RESOURCE_OXYGEN },
    [RESOURCE_GHODIUM_HYDRIDE]: { rct1: RESOURCE_GHODIUM, rct2: RESOURCE_HYDROGEN },

    // 二级化合物
    [RESOURCE_UTRIUM_ALKALIDE]: { rct1: RESOURCE_UTRIUM_OXIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_UTRIUM_ACID]: { rct1: RESOURCE_UTRIUM_HYDRIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_ZYNTHIUM_ALKALIDE]: { rct1: RESOURCE_ZYNTHIUM_OXIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_ZYNTHIUM_ACID]: { rct1: RESOURCE_ZYNTHIUM_HYDRIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_KEANIUM_ALKALIDE]: { rct1: RESOURCE_KEANIUM_OXIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_KEANIUM_ACID]: { rct1: RESOURCE_KEANIUM_HYDRIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_LEMERGIUM_ALKALIDE]: { rct1: RESOURCE_LEMERGIUM_OXIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_LEMERGIUM_ACID]: { rct1: RESOURCE_LEMERGIUM_HYDRIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_GHODIUM_ALKALIDE]: { rct1: RESOURCE_GHODIUM_OXIDE, rct2: RESOURCE_HYDROXIDE },
    [RESOURCE_GHODIUM_ACID]: { rct1: RESOURCE_GHODIUM_HYDRIDE, rct2: RESOURCE_HYDROXIDE },

    // 三级化合物
    [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: { rct1: RESOURCE_UTRIUM_ALKALIDE, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_UTRIUM_ACID]: { rct1: RESOURCE_UTRIUM_ACID, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: { rct1: RESOURCE_ZYNTHIUM_ALKALIDE, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: { rct1: RESOURCE_ZYNTHIUM_ACID, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: { rct1: RESOURCE_KEANIUM_ALKALIDE, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_KEANIUM_ACID]: { rct1: RESOURCE_KEANIUM_ACID, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: { rct1: RESOURCE_LEMERGIUM_ALKALIDE, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_LEMERGIUM_ACID]: { rct1: RESOURCE_LEMERGIUM_ACID, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: { rct1: RESOURCE_GHODIUM_ALKALIDE, rct2: RESOURCE_CATALYST },
    [RESOURCE_CATALYZED_GHODIUM_ACID]: { rct1: RESOURCE_GHODIUM_ACID, rct2: RESOURCE_CATALYST },
}

export const BaseMineral = [
    RESOURCE_HYDROGEN, RESOURCE_OXYGEN,
    RESOURCE_KEANIUM, RESOURCE_UTRIUM, RESOURCE_LEMERGIUM, RESOURCE_ZYNTHIUM,
    RESOURCE_CATALYST
]

export const LabTarget = {
    // 基础
    OH: [
        { target: RESOURCE_HYDROXIDE, amount: 3000 },
        { target: RESOURCE_ZYNTHIUM_KEANITE, amount: 300 },
        { target: RESOURCE_UTRIUM_LEMERGITE, amount: 300 },
        { target: RESOURCE_GHODIUM, amount: 6000 },
    ],
    G: [
        // XGH2O 生产线，强化 WORK 的 upgrade
        { target: RESOURCE_GHODIUM_HYDRIDE, amount: 2000 }, 
        { target: RESOURCE_GHODIUM_ACID, amount: 3000 }, 
        { target: RESOURCE_CATALYZED_GHODIUM_ACID, amount: 4000 }, 
        // XGHO2 生产线，强化 TOUGH
        { target: RESOURCE_GHODIUM_OXIDE, amount: 200 }, 
        { target: RESOURCE_GHODIUM_ALKALIDE, amount: 3000 }, 
        { target: RESOURCE_CATALYZED_GHODIUM_ALKALIDE, amount: 4000 },
    ],
    U: [
        { target: RESOURCE_UTRIUM_LEMERGITE, amount: 2000 },
        { target: RESOURCE_GHODIUM, amount: 5000 },
        // XUH2O 生产线，强化 ATTACK
        { target: RESOURCE_UTRIUM_HYDRIDE, amount: 2000 },
        { target: RESOURCE_UTRIUM_ACID, amount: 3000 },
        { target: RESOURCE_CATALYZED_UTRIUM_ACID, amount: 4000 },
        // XUHO2 生产线，强化 HARVEST
        { target: RESOURCE_UTRIUM_OXIDE, amount: 2000 },
        { target: RESOURCE_UTRIUM_ALKALIDE, amount: 3000 },
        { target: RESOURCE_CATALYZED_UTRIUM_ALKALIDE, amount: 4000 },
    ],
    K: [
        { target: RESOURCE_ZYNTHIUM_KEANITE, amount: 2000 },
        { target: RESOURCE_GHODIUM, amount: 5000 },
        // XKH2O 生产线，强化 CARRY
        { target: RESOURCE_KEANIUM_HYDRIDE, amount: 2000 },
        { target: RESOURCE_KEANIUM_ACID, amount: 3000 },
        { target: RESOURCE_CATALYZED_KEANIUM_ACID, amount: 4000 },
        // XKHO2 生产线，强化 RANGE_ATTACK
        { target: RESOURCE_KEANIUM_OXIDE, amount: 2000 }, 
        { target: RESOURCE_KEANIUM_ALKALIDE, amount: 3000 }, 
        { target: RESOURCE_CATALYZED_KEANIUM_ALKALIDE, amount: 4000 },  
    ],
    L: [
        { target: RESOURCE_UTRIUM_LEMERGITE, amount: 2000 },
        { target: RESOURCE_GHODIUM, amount: 5000 },
        // XLH2O 生产线，强化 WORK 的 repair/build
        { target: RESOURCE_LEMERGIUM_HYDRIDE, amount: 2000 }, 
        { target: RESOURCE_LEMERGIUM_ACID, amount: 3000 }, 
        { target: RESOURCE_CATALYZED_LEMERGIUM_ACID, amount: 4000 }, 
        // XLHO2 生产线，强化 HEAL
        { target: RESOURCE_LEMERGIUM_OXIDE, amount: 2000 }, 
        { target: RESOURCE_LEMERGIUM_ALKALIDE, amount: 3000 }, 
        { target: RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE, amount: 4000 },
    ],
    Z: [
        { target: RESOURCE_ZYNTHIUM_KEANITE, amount: 2000 },
        { target: RESOURCE_GHODIUM, amount: 5000 },
        // XZH2O 生产线，强化 WORK 的 dismantle
        { target: RESOURCE_ZYNTHIUM_HYDRIDE, amount: 2000 }, 
        { target: RESOURCE_ZYNTHIUM_ACID, amount: 3000 }, 
        { target: RESOURCE_CATALYZED_ZYNTHIUM_ACID, amount: 4000 }, 
        // XZHO2 生产线，强化 MOVE
        { target: RESOURCE_ZYNTHIUM_OXIDE, amount: 2000 }, 
        { target: RESOURCE_ZYNTHIUM_ALKALIDE, amount: 3000 }, 
        { target: RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE, amount: 4000 },
    ]
}